### PR TITLE
Update awsu to 2.3.2

### PR DESCRIPTION
**Pull request by nauxliu**

### CODE REVIEW

**Comment by nauxliu** [comment]
@yawn

**Comment by yawn** [comment]
Thanks @nauxliu !

**Comment by RayNeumann** [comment]
Hey guys,


Can you please remove my email from your list?

I keep getting updates from kreuzwerker.

Cheers,
Ray.

**Comment by nauxliu** [comment]
@RayNeumann I see that you are watching this repo, you can unsubscribe by simply canceling this repo.

**Pull request merged**
